language: python
python: "2.7"
sudo: false
branches:
     only:
          - release1.0     
before_script: ./build/scripts/setup_credentials.sh
script: ./build/scripts/deploy.sh
notifications: 
    slack: shantanu0805:G6gDQ7s7HqJng2e84QEDwq5m     
email:
    recipients:
      # - shantanu0805@gmail.com
    on_success: always # default: change
    on_failure: always # default: always